
int bitXor(int, int);
int test_bitXor(int, int);
int byteSwap(int, int, int);
int test_byteSwap(int, int, int);
int reverseBytes(int);
int test_reverseBytes(int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int minusOne();
int test_minusOne();
int isTmax(int);
int test_isTmax(int);
int isNegative(int);
int test_isNegative(int);
int negate(int);
int test_negate(int);
int subOK(int, int);
int test_subOK(int, int);
int rempwr2(int, int);
int test_rempwr2(int, int);
int isLessOrEqual(int, int);
int test_isLessOrEqual(int, int);
int ezThreeFourths(int);
int test_ezThreeFourths(int);
int tc2sm(int);
int test_tc2sm(int);
unsigned float_neg(unsigned);
unsigned test_float_neg(unsigned);
unsigned float_i2f(int);
unsigned test_float_i2f(int);
